SHELL=bash
WD:=$(shell pwd)

# by default
nothing:

diff:
	for i in *.bsh; do echo $$i; diff $$i $(HOME)/neuroidnet/scripts/$$i; done

commit:
	cd ../..; cp -f $(WD)/*.bsh scripts/
	cp -f Makefile ../Makefile.trace
